services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DATABASE_DRIVER: "org.h2.Driver"
      DATABASE_URL: "jdbc:h2:mem:artdigitaldb"
      DATABASE_USER: "sa"
      DATABASE_PASS: ""
      DATABASE_DIALECT: "org.hibernate.dialect.H2Dialect"
      JWT_SECRET: "ec784fa5-3825-4f41-a147-c3e7ae111d17"
